name: Metrics for Repositories and Diff History
on:
  push:
    branches:
      - master
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Example
      uses: lowlighter/metrics@latest
      with:
        template: terminal
        filename: metrics.terminal.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, metadata
